### ISSUE TITLE
Email user when results are done

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#109]
Workflows often take a very long time. Would be good to give users an option to receive an email notification that their results (or errors) are available, which could include a link to directly go to those results.

**Comment by shawnawsu** [comment]
Hi @mestato, 

Were you thinking it would be at a user level or a workflow level that you could choose to receive a notification email?

Thanks!

**Comment by mestato** [comment]
I was thinking per workflow. At the submit step, have a checkbox for "Be notified by email when this workflow completes"

**Comment by shawnawsu** [comment]
It appears as though an email should be sent when the run is complete already, there are two functions: `tripal_galaxy_send_submission_ended_mail` and `tripal_galaxy_send_submission_failed_mail`. I can see failed mail attempts in my log because my local isn't setup to send mail, can you check the log of your site to see if you're seeing the same errors? I'm going to change this to a bug.

**Comment by MingChen0919** [comment]
I got this error in the HGD site: `There was a problem sending your message and it was not sent.`

**Comment by spficklin** [comment]
@MingChen0919 as per https://github.com/tripal/tripal_galaxy/pull/119#issuecomment-429419161 that you made on Oct 12th I think this is fixed for you?  If so we can close this out.

**Comment by mestato** [comment]
We got it working! Thanks for the help!
