### ISSUE TITLE
Workflow status stuck on Submitted

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#141]
Workflow invoked with Tripal Galaxy API gets its status stuck in "Submitted" (i.e., it doesn't update to "Completed" when Galaxy finishes executing the workflow).

URL: %Tripal_instance%/user/user_id/galaxy-jobs?status=All&workflow_name=

**Comment by shawnawsu** [comment]
Is your cron configured to run the galaxy status check?

https://tripal-galaxy.readthedocs.io/en/latest/automating_tasks.html#automatic-job-status-checking

**Comment by NicHerndon** [comment]
@Sean?

**Comment by Ferrisx4** [comment]
The Galaxy checking is being handled by the built-in Drupal cron (as opposed to setting it up with a regular crontab):

![DrupalCron](https://user-images.githubusercontent.com/9593623/57139951-89694900-6d84-11e9-92ff-d7de29f554fd.png)

For some reason, jobs are not being queued up in the Tripal Job queue on this server (they are being queued and run successfully on the production server) - looking into configuration differences now. 

Running the command from the linked documentation manually: `drush trp-galaxy-status --uri=http://my.tripal.site/ --root=/var/www/html
` results in an error: 
```Updating status of all workflows...
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2>

<p>TypeError: Argument 2 passed to tripal_galaxy_get_history() must be of the type string, null given, called in /var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc on line 555 in tripal_galaxy_get_history() (line 1014 of /var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc).</p>

<h2>Additional</h2>

<p>TYPO3\PharStreamWrapper\Exception: Unexpected file extension in &amp;quot;phar:///usr/bin/drush/commands/core/drupal&amp;quot; in Drupal\Core\Security\PharExtensionInterceptor-&gt;assert() (line 38 of /var/www/Drupal/misc/typo3/drupal-security/PharExtensionInterceptor.php).</p><hr />Drush command terminated abnormally due to an unrecoverable error.
```

**Comment by shawnawsu** [comment]
Hi @Ferrisx4 ,

Just following up, did you figure out what the problem was? If you setup a proper crontab for Tripal Galaxy does the job run?

Thanks,
Shawna

**Comment by Ferrisx4** [comment]
Hi @shawnawsu 

Setting up a crontab with the command from the linked documentation does not work. 
The error that that command returns points at the tripal_galaxy_drush_command() function, which calls the tripal_galaxy_check_submission() function. From there, the active submissions are fetched from the database.

I suspect a database state issue on our end because [this line](https://github.com/tripal/tripal_galaxy/blob/36f2cf84ef61874cff13ad2c202aab28dadc633c/api/tripal_galaxy.api.inc#L554) returns null, which inspires the error:

`TypeError: Argument 2 passed to tripal_galaxy_get_history() must be of the type string, null given, called in /var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc on line 555 in tripal_galaxy_get_history() (line 1014 of /var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc).`

I'm comparing the contents of a database that seems to be working and the one on our dev server (the one in question now). Perhaps tripal_galaxy's database schema changed at one point and there are rows that have no data in a specific column which this function is looking for.

**Comment by spficklin** [comment]
I believe PR #144 fixes this. The PR is merged.  Please comment if the problem persists.
