### ISSUE TITLE
Deleting Galaxy Instance

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#29]
Deleting an instance gives:
```Recoverable fatal error: Argument 2 passed to db_query() must be of the type array, string given, called in /var/www/html/sites/all/modules/tripal-extensions/tripal_galaxy/includes/tripal_galaxy.admin_configuration_form.inc on line 128 and defined in db_query() (line 2401 of /var/www/html/includes/database/database.inc).```

**Comment by cwytko** [comment]
@mestato, botched the db_delete query, should be fixed now, please confirm when you have time

**Comment by mestato** [comment]
I checked out branch issue_29 and it worked to delete the instance, but it did not delete the associated workflows. I expected it to, but maybe this was a conscious decision? Those workflows won't run without the instance, but then again, they may be associated with preexisting user jobs - what should happen to those when a galaxy instance disappears?

**Comment by spficklin** [comment]
Hmm... this one will take some thought.  We don't want user's workflows disappearing on them.  But I hate it when software won't let me delete something that I really want to delete.  Perhaps we keep the delete and update it so it can remove all dependent workflows on delete.  Also, we could add a disable button so that a site admin can easily turn off all workflows without removing end-user's workflow results.

**Comment by spficklin** [comment]
The delete now removes the workflows and all user submissions for the workflow if the Galaxy instance is removed. It also now gives you the option to confirm deletion with a warning message of the mayhem that will occur for users.   I've tested that it works.   We still need a way to disable all workflows for a given galaxy instance without deleting it.  But I'll add that as a separate issue.
