### ISSUE TITLE
TopHat's built in reference genome/user selected file from history

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#7]
This option is not being presented on the tripal front end.
Need to verify that the correct **prebuilt** option is in place.

**Comment by MingChen0919** [comment]
@cwytko Should I disable the built-in reference genome option for all workflows?

**Comment by cwytko** [comment]
@MingChen0919 for now yes.
Allow me to fix the issue with the invoke (the latest issue).
When Stephen and I merged, the workflow invoke function got messed up.
Once I fix this function I'll look into why this options is also messed up.

**Comment by cwytko** [comment]
@MingChen0919 
Update: The invoke is working but error handling in the workflow if it has a messed up input is **uncaught** and not directly visible through tripal.
I'll work on #10  later then.
Right now I'm going to fix our results page to simply present the output files from the workflow that galaxy spits out.
If there's more meta-data(ish) things you want to see let me know!

**Comment by cwytko** [comment]
Another tool that uses a similar set up is the **MiRDeep2 Mapper** tool

**Comment by cwytko** [comment]
Another tool that has the same issue **Map with BWA**

**Comment by spficklin** [comment]
Is this issue resolved?

**Comment by spficklin** [comment]
@MingChen0919 and @cwytko .  Can either of you verify if this issue is fixed?  I'm trying to clean up old issues and we've fixed so many things it's not clear to me if this is still a problem.

**Comment by MingChen0919** [comment]
When tools are used in a workflow, some options are automatically disabled. These options are not available because it changes the structure (the number of inputs and outputs) and therefore it breaks the workflow. These options are defined in a <conditional></conditional> tag in the galaxy tool config file. This is not a tripal galaxy module issue. It happens even you run the workflow in Galaxy directory. Someone can close this issue.
